update lambda module

diff --git a/.github/workflows/chatbot-deploy.yml b/.github/workflows/chatbot-deploy.yml
--- a/.github/workflows/chatbot-deploy.yml
+++ b/.github/workflows/chatbot-deploy.yml
@@ -75,124 +75,123 @@ jobs:
   #         repo_name: "${{ env.PROJECT_NAME }}-update-knowledge-base"
   #       working-directory: "batch_docker_image"
   #       id: run_tag_and_push  
+Terraform:
+  if: always()  # Ensure this job runs regardless of previous outcomes
+  runs-on: ubuntu-latest
+  needs: [PrepareFilter]  # Add Docker Image later
+  environment: staging  # Requires manual approval through GitHub Environments
+  defaults:
+    run:
+      shell: bash
+      working-directory: 'terraform'
+  steps:
+    - name: Git clone the repository
+      uses: actions/checkout@v4
 
-  Terraform:
-    if: always()  # Ensure this job runs regardless of previous outcomes
-    runs-on: ubuntu-latest
-    needs: [PrepareFilter]  # Add Docker Image later
-    environment: staging  # Requires manual approval through GitHub Environments
-    defaults:
-      run:
-        shell: bash
-        working-directory: 'terraform'
-    steps:
-      - name: Git clone the repository
-        uses: actions/checkout@v4
+    - name: Setup Python  # Add Python setup step here
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.12'
 
-      - name: Setup Python  # Add Python setup step here
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.12'
+    - name: Check Python version
+      run: python --version
 
-      - name: Check Python version
-        run: python --version
+    - name: Check pip version
+      run: pip --version
 
-      - name: Check pip version
-        run: pip --version
+    - name: Install dependencies
+      run: |
+        if [ -s ${GITHUB_WORKSPACE}/layer/requirements.txt ]; then
+          pip install -r ${GITHUB_WORKSPACE}/layer/requirements.txt -t ${GITHUB_WORKSPACE}/layer/python/lib/python3.12/site-packages || { echo 'Failed to install requirements'; exit 1; }
+        fi
+        pip install pytest boto3 || { echo 'Pip install for pytest and boto3 failed'; exit 1; }
 
-      - name: Install dependencies
-        run: |
-          if [ -s ${GITHUB_WORKSPACE}/layer/requirements.txt ]; then
-            pip install -r ${GITHUB_WORKSPACE}/layer/requirements.txt -t ${GITHUB_WORKSPACE}/layer/python/lib/python3.12/site-packages || { echo 'Failed to install requirements'; exit 1; }
-          fi
-          pip install pytest boto3 || { echo 'Pip install for pytest and boto3 failed'; exit 1; }
+    - name: Run tests
+      run: |
+        if [ -d "${GITHUB_WORKSPACE}/tests" ]; then
+          pytest ${GITHUB_WORKSPACE}/tests || { echo 'Tests failed'; exit 1; }
+        else
+          echo "Tests folder does not exist, skipping tests."
+        fi
 
-      - name: Run tests
-        run: |
-          if [ -d "${GITHUB_WORKSPACE}/tests" ]; then
-            pytest ${GITHUB_WORKSPACE}/tests || { echo 'Tests failed'; exit 1; }
-          else
-            echo "Tests folder does not exist, skipping tests."
-          fi
+    - name: Configure AWS credentials
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        role-to-assume: arn:aws:iam::992382467535:role/oidc-github-role
+        role-session-name: samplerolesession
+        aws-region: eu-central-1
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: arn:aws:iam::992382467535:role/oidc-github-role
-          role-session-name: samplerolesession
-          aws-region: eu-central-1
+    - name: Create statefile bucket
+      run: |
+        if aws s3api head-bucket --bucket "${{ env.PROJECT_NAME }}-statefile-bucket-tf-${{ env.ACCOUNT_ID }}" 2>/dev/null; then
+          echo "Bucket already exists."
+        else
+          aws s3api create-bucket --bucket "${{ env.PROJECT_NAME }}-statefile-bucket-tf-${{ env.ACCOUNT_ID }}" --region "${{ env.REGION }}" --create-bucket-configuration LocationConstraint="${{ env.REGION }}"
+          aws dynamodb create-table \
+            --table-name "${{ env.PROJECT_NAME }}-tf-lock" \
+            --attribute-definitions AttributeName=LockID,AttributeType=S \
+            --key-schema AttributeName=LockID,KeyType=HASH \
+            --billing-mode PAY_PER_REQUEST \
+            --deletion-protection-enabled \
+            --tags Key=CreatedBy,Value='Github Actions',Key=map-migrated,Value="${{ env.MAP_TAG }}",Key=ProjectName,Value="${{ env.PROJECT_NAME }}"
+        fi
 
-      - name: Create statefile bucket
-        run: |
-          if aws s3api head-bucket --bucket "${{ env.PROJECT_NAME }}-statefile-bucket-tf-${{ env.ACCOUNT_ID }}" 2>/dev/null; then
-            echo "Bucket already exists."
-          else
-            aws s3api create-bucket --bucket "${{ env.PROJECT_NAME }}-statefile-bucket-tf-${{ env.ACCOUNT_ID }}" --region "${{ env.REGION }}" --create-bucket-configuration LocationConstraint="${{ env.REGION }}"
-            aws dynamodb create-table \
-              --table-name "${{ env.PROJECT_NAME }}-tf-lock" \
-              --attribute-definitions AttributeName=LockID,AttributeType=S \
-              --key-schema AttributeName=LockID,KeyType=HASH \
-              --billing-mode PAY_PER_REQUEST \
-              --deletion-protection-enabled \
-              --tags Key=CreatedBy,Value='Github Actions',Key=map-migrated,Value="${{ env.MAP_TAG }}",Key=ProjectName,Value="${{ env.PROJECT_NAME }}"
-          fi
+        aws s3api put-bucket-tagging --bucket "${{ env.PROJECT_NAME }}-statefile-bucket-tf-${{ env.ACCOUNT_ID }}" --tagging 'TagSet=[{Key=CreatedBy,Value="Github Actions2"},{Key=map-migrated,Value="${{ env.MAP_TAG }}"},{Key=ProjectName,Value="${{ env.PROJECT_NAME }}"}}]'
+        aws s3api put-bucket-versioning --bucket "${{ env.PROJECT_NAME }}-statefile-bucket-tf-${{ env.ACCOUNT_ID }}" --region "${{ env.REGION }}" --versioning-configuration Status=Enabled
+        aws s3api put-bucket-encryption --bucket "${{ env.PROJECT_NAME }}-statefile-bucket-tf-${{ env.ACCOUNT_ID }}" --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"aws:kms","KMSMasterKeyID":"arn:aws:kms:${{ env.REGION }}:${{ env.ACCOUNT_ID }}:alias/aws/s3"}}]}'
 
-          aws s3api put-bucket-tagging --bucket "${{ env.PROJECT_NAME }}-statefile-bucket-tf-${{ env.ACCOUNT_ID }}" --tagging 'TagSet=[{Key=CreatedBy,Value="Github Actions2"},{Key=map-migrated,Value="${{ env.MAP_TAG }}"},{Key=ProjectName,Value="${{ env.PROJECT_NAME }}"}}]'
-          aws s3api put-bucket-versioning --bucket "${{ env.PROJECT_NAME }}-statefile-bucket-tf-${{ env.ACCOUNT_ID }}" --region "${{ env.REGION }}" --versioning-configuration Status=Enabled
-          aws s3api put-bucket-encryption --bucket "${{ env.PROJECT_NAME }}-statefile-bucket-tf-${{ env.ACCOUNT_ID }}" --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"aws:kms","KMSMasterKeyID":"arn:aws:kms:${{ env.REGION }}:${{ env.ACCOUNT_ID }}:alias/aws/s3"}}]}'
+    - name: Get Image Tag
+      id: getimagetag
+      run: |
+        DOCKER_IMAGE_TAG=$(aws ssm get-parameter --name docker_image_tag --output text --query Parameter.Value)
+        if [ $? -ne 0 ]; then
+          echo "Failed to get Docker image tag from SSM."
+          exit 1
+        fi
+        echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG"
+        echo "image_tag=$DOCKER_IMAGE_TAG" >> $GITHUB_ENV
 
-      - name: Get Image Tag
-        id: getimagetag
-        run: |
-          DOCKER_IMAGE_TAG=$(aws ssm get-parameter --name docker_image_tag --output text --query Parameter.Value)
-          if [ $? -ne 0 ]; then
-            echo "Failed to get Docker image tag from SSM."
-            exit 1
-          fi
-          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG"
-          echo "image_tag=$DOCKER_IMAGE_TAG" >> $GITHUB_ENV
+    - name: Terraform init
+      id: init
+      run: |
+        terraform init -backend-config="bucket=${{ env.PROJECT_NAME }}-statefile-bucket-tf-${{ env.ACCOUNT_ID }}" -backend-config="dynamodb_table=${{ env.PROJECT_NAME }}-tf-lock"
+        terraform providers
 
-      - name: Terraform init
-        id: init
-        run: |
-          terraform init -backend-config="bucket=${{ env.PROJECT_NAME }}-statefile-bucket-tf-${{ env.ACCOUNT_ID }}" -backend-config="dynamodb_table=${{ env.PROJECT_NAME }}-tf-lock"
-          terraform providers
+    - name: Terraform apply
+      id: apply
+      run: |
+        terraform apply -auto-approve -var 'project_name=${{ env.PROJECT_NAME }}' -var 'account_id=${{ env.ACCOUNT_ID }}' -var 'region=${{ env.REGION }}' -var 'map_tag=${{ env.MAP_TAG }}' -var 'image_tag=${{ env.image_tag }}'
 
-      - name: Terraform apply
-        id: apply
-        run: |
-          terraform apply -auto-approve -var 'project_name=${{ env.PROJECT_NAME }}' -var 'account_id=${{ env.ACCOUNT_ID }}' -var 'region=${{ env.REGION }}' -var 'map_tag=${{ env.MAP_TAG }}' -var 'image_tag=${{ env.image_tag }}'
+TerraformDestroy:
+  if: always()  # Ensures that destroy runs even if the apply step fails
+  runs-on: ubuntu-latest
+  needs: Terraform
+  environment: production  # Requires manual approval for destroy step
+  defaults:
+    run:
+      shell: bash
+      working-directory: 'terraform'  # Ensure Terraform is run in the correct directory
+  steps:
+    - name: Git clone the repository
+      uses: actions/checkout@v4
 
-  TerraformDestroy:
-    if: always()  # Ensures that destroy runs even if the apply step fails
-    runs-on: ubuntu-latest
-    needs: Terraform
-    environment: production  # Requires manual approval for destroy step
-    defaults:
-      run:
-        shell: bash
-        working-directory: 'terraform'  # Ensure Terraform is run in the correct directory
-    steps:
-      - name: Git clone the repository
-        uses: actions/checkout@v4
+    - name: Configure AWS credentials
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        role-to-assume: arn:aws:iam::992382467535:role/oidc-github-role
+        aws-region: eu-central-1
+        role-session-name: oidc-session
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: arn:aws:iam::992382467535:role/oidc-github-role
-          aws-region: eu-central-1
-          role-session-name: oidc-session
+    - name: List files in the working directory  # Debugging step
+      run: ls -la
 
-      - name: List files in the working directory  # Debugging step
-        run: ls -la
-
-      - name: Terraform init and destroy
-        run: |
-          terraform init -backend-config="bucket=${{ env.PROJECT_NAME }}-statefile-bucket-tf-${{ env.ACCOUNT_ID }}" \
-                         -backend-config="dynamodb_table=${{ env.PROJECT_NAME }}-tf-lock"
-          terraform destroy -auto-approve \
-            -var "project_name=${{ env.PROJECT_NAME }}" \
-            -var "account_id=${{ env.ACCOUNT_ID }}" \
-            -var "region=${{ env.REGION }}" \
-            -var "map_tag=${{ env.MAP_TAG }}" \
-            -var "image_tag=${{ env.image_tag }}"
+    - name: Terraform init and destroy
+      run: |
+        terraform init -backend-config="bucket=${{ env.PROJECT_NAME }}-statefile-bucket-tf-${{ env.ACCOUNT_ID }}" \
+                       -backend-config="dynamodb_table=${{ env.PROJECT_NAME }}-tf-lock"
+        terraform destroy -auto-approve \
+          -var "project_name=${{ env.PROJECT_NAME }}" \
+          -var "account_id=${{ env.ACCOUNT_ID }}" \
+          -var "region=${{ env.REGION }}" \
+          -var "map_tag=${{ env.MAP_TAG }}" \
+          -var "image_tag=${{ env.image_tag }}"
